package com.acerstore.app.main;

import com.acerstore.app.menu.MenuEvent;
import java.awt.Component;
import com.acerstore.app.view.*;
import java.awt.Color;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

public class MainFrame extends JFrame {

    public MainFrame() {
        initComponents();
        setForm();
        menu.setEvent(new MenuEvent() {
            @Override
            public void selected(int index, int subIndex) {
                if (index == 0) {
                    showForm(new TrangChu());
                }
                if (index == 1) {
                    showForm(new BanHang());
                }
                if (index == 2) {
                    showForm(new HoaDon());
                }
                if (index == 3) {
                    showForm(new SanPham());
                }
                if (index == 4) {
                    showForm(new KhuyenMai());
                }
                if (index == 5) {
                    showForm(new KhachHang());
                }
                if (index == 6) {
                    showForm(new NhanVien());
                }

                if (index == 8 && subIndex == 1) {
                    logOut();
                }

                if (index == 10) {
                    exitForm();
                }
            }
        });
    }

    private void showForm(Component com) {
        pnlComponent.removeAll();
        pnlComponent.add(com);
        pnlComponent.repaint();
        pnlComponent.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContainer = new javax.swing.JPanel();
        scrollPane1 = new com.acerstore.app.swing.ScrollPane();
        menu = new com.acerstore.app.menu.Menu();
        header = new com.acerstore.app.view.Header();
        pnlComponent = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        pnlContainer.setBackground(new java.awt.Color(245, 245, 245));
        pnlContainer.setPreferredSize(new java.awt.Dimension(1536, 81));

        scrollPane1.setBorder(null);
        scrollPane1.setViewportView(menu);

        pnlComponent.setBackground(new java.awt.Color(255, 255, 255));
        pnlComponent.setPreferredSize(new java.awt.Dimension(1272, 757));
        pnlComponent.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout pnlContainerLayout = new javax.swing.GroupLayout(pnlContainer);
        pnlContainer.setLayout(pnlContainerLayout);
        pnlContainerLayout.setHorizontalGroup(
            pnlContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContainerLayout.createSequentialGroup()
                .addComponent(scrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlComponent, javax.swing.GroupLayout.DEFAULT_SIZE, 1326, Short.MAX_VALUE))
            .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlContainerLayout.setVerticalGroup(
            pnlContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContainerLayout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlContainerLayout.createSequentialGroup()
                        .addComponent(pnlComponent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(3, 3, 3))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 820, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.acerstore.app.view.Header header;
    private com.acerstore.app.menu.Menu menu;
    private javax.swing.JPanel pnlComponent;
    private javax.swing.JPanel pnlContainer;
    private com.acerstore.app.swing.ScrollPane scrollPane1;
    // End of variables declaration//GEN-END:variables

    private void logOut() {
        int rs = JOptionPane.showConfirmDialog(rootPane, "Bạn có muốn đăng xuất tài khoản?",
                "Acer Store - Đăng xuất", JOptionPane.YES_NO_OPTION);
        if (rs == JOptionPane.YES_OPTION) {
            setVisible(false);
            new DangNhap().setVisible(true);
        }
    }

    private void exitForm() {
        int exit = JOptionPane.showConfirmDialog(rootPane, "Bạn có muốn thoát?",
                "Acer Store - Thoát", JOptionPane.YES_NO_OPTION);
        if (exit == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }

    private void setForm() {
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }
}
