/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Dialog.java to edit this template
 */
package Interfaces;

import com.acerstore.app.dao.SanPhamChiTietDao;
import com.acerstore.app.model.ManHinh;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JeongDoo
 */
public class ManHinhhJDaLog extends java.awt.Dialog {

    DefaultTableModel tblmodel;
    SanPhamChiTietDao spcdao = new SanPhamChiTietDao();

    public ManHinhhJDaLog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        filltoTableMh(spcdao.getMH());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txtTenMh6 = new javax.swing.JTextField();
        btnAdd6 = new javax.swing.JButton();
        btnDelete6 = new javax.swing.JButton();
        btnUpdate6 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        rdoHD6 = new javax.swing.JRadioButton();
        rdoKHD6 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblManHinh = new javax.swing.JTable();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Màn Hình", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N

        jLabel13.setText("Tên");

        btnAdd6.setText("ADD");
        btnAdd6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnDelete6.setText("Delete");
        btnDelete6.setEnabled(false);
        btnDelete6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnUpdate6.setText("Update");
        btnUpdate6.setEnabled(false);
        btnUpdate6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        jLabel14.setText("Trạng thái");

        rdoHD6.setSelected(true);
        rdoHD6.setText("Hoạt động");

        rdoKHD6.setText("Không hoạt động");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(59, 59, 59)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTenMh6, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnAdd6)
                                    .addComponent(rdoHD6))
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(rdoKHD6))
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addComponent(btnUpdate6)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnDelete6)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTenMh6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(rdoHD6)
                    .addComponent(rdoKHD6))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd6)
                    .addComponent(btnUpdate6)
                    .addComponent(btnDelete6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel7, java.awt.BorderLayout.CENTER);

        tblManHinh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Tên màn hình", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblManHinh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblManHinhMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblManHinh);

        add(jScrollPane1, java.awt.BorderLayout.NORTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        this.updateMH();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        this.deleteMh();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        this.addManHinh();
    }//GEN-LAST:event_btnAddActionPerformed

    private void tblManHinhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblManHinhMouseClicked
        // TODO add your handling code here:
        int index = tblManHinh.getSelectedRow();
        showDetailMh(index);
        btnUpdate.setEnabled(true);
        btnDelete.setEnabled(true);
    }//GEN-LAST:event_tblManHinhMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ManHinhhJDaLog dialog = new ManHinhhJDaLog(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAdd1;
    private javax.swing.JButton btnAdd2;
    private javax.swing.JButton btnAdd3;
    private javax.swing.JButton btnAdd4;
    private javax.swing.JButton btnAdd5;
    private javax.swing.JButton btnAdd6;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDelete1;
    private javax.swing.JButton btnDelete2;
    private javax.swing.JButton btnDelete3;
    private javax.swing.JButton btnDelete4;
    private javax.swing.JButton btnDelete5;
    private javax.swing.JButton btnDelete6;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnUpdate1;
    private javax.swing.JButton btnUpdate2;
    private javax.swing.JButton btnUpdate3;
    private javax.swing.JButton btnUpdate4;
    private javax.swing.JButton btnUpdate5;
    private javax.swing.JButton btnUpdate6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdoHD;
    private javax.swing.JRadioButton rdoHD1;
    private javax.swing.JRadioButton rdoHD2;
    private javax.swing.JRadioButton rdoHD3;
    private javax.swing.JRadioButton rdoHD4;
    private javax.swing.JRadioButton rdoHD5;
    private javax.swing.JRadioButton rdoHD6;
    private javax.swing.JRadioButton rdoKHD;
    private javax.swing.JRadioButton rdoKHD1;
    private javax.swing.JRadioButton rdoKHD2;
    private javax.swing.JRadioButton rdoKHD3;
    private javax.swing.JRadioButton rdoKHD4;
    private javax.swing.JRadioButton rdoKHD5;
    private javax.swing.JRadioButton rdoKHD6;
    private javax.swing.JTable tblManHinh;
    private javax.swing.JTextField txtTenMh;
    private javax.swing.JTextField txtTenMh1;
    private javax.swing.JTextField txtTenMh2;
    private javax.swing.JTextField txtTenMh3;
    private javax.swing.JTextField txtTenMh4;
    private javax.swing.JTextField txtTenMh5;
    private javax.swing.JTextField txtTenMh6;
    // End of variables declaration//GEN-END:variables

    private void filltoTableMh(List<ManHinh> manhinh) {
        tblmodel = (DefaultTableModel) tblManHinh.getModel();
        tblmodel.setRowCount(0);
        for (ManHinh mh : manhinh) {
            tblmodel.addRow(new Object[]{
                mh.getIdMh(),
                mh.getTenMh(),
                mh.isTrangThai() ? "Hoạt động" : "Không hoạt động"
            });
        }
    }

    private ManHinh readDataMh() {
        int id = 0;
        String ten = txtTenMh.getText();
        boolean tt;
        if (tt = rdoHD.isSelected()) {
            tt = true;
        } else {
            tt = false;
        }
        return new ManHinh(id, ten, tt);
    }

    private void addManHinh() {
        if (checkDataMh()) {
            ManHinh mh = readDataMh();
            if (spcdao.AddManHinh(mh) > 0) {
                JOptionPane.showMessageDialog(this, "add successful");
                filltoTableMh(spcdao.getMH());
            } else {
                JOptionPane.showMessageDialog(this, "add failed");
            }
        }
    }

    private void deleteMh() {
        int index = tblManHinh.getSelectedRow();
        int id = Integer.parseInt(tblManHinh.getValueAt(index, 0).toString());
        if (spcdao.deleteMH(id) > 0) {
            JOptionPane.showMessageDialog(this, "delete successful");
            filltoTableMh(spcdao.getMH());
        } else {
            JOptionPane.showMessageDialog(this, "delete failed");
        }
        txtTenMh.setText("");
        rdoHD.isSelected();
        btnDelete.setEnabled(false);
    }

    private void updateMH() {
        if (checkDataMh()) {
            ManHinh mh = readDataMh();
            int index = tblManHinh.getSelectedRow();
            int id = Integer.parseInt(tblManHinh.getValueAt(index, 0).toString());
            if (spcdao.updateMh(mh, id) > 0) {
                JOptionPane.showMessageDialog(this, "update successful");
                filltoTableMh(spcdao.getMH());
            } else {
                JOptionPane.showMessageDialog(this, "update failed");
            }
            txtTenMh.setText("");
            rdoHD.isSelected();
            btnUpdate.setEnabled(false);
        }
    }

    private void showDetailMh(int index) {
        ManHinh mh = spcdao.getMH().get(index);
        txtTenMh.setText(mh.getTenMh());
        rdoHD.setSelected(mh.isTrangThai());
        tblManHinh.setRowSelectionInterval(index, index);
    }

    private boolean checkDataMh() {
        if (txtTenMh.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "empty");
            txtTenMh.requestFocus();
            return false;
        }
        return true;
    }
}
