package Interfaces;

import com.acerstore.app.dao.SanPhamChiTietDao;
import com.acerstore.app.dao.SanPhamDao;
import com.acerstore.app.database.DBConnection;
import com.acerstore.app.model.CPU;
import com.acerstore.app.model.HeDieuHanh;
import com.acerstore.app.model.Imei;
import com.acerstore.app.model.KichThuoc;
import com.acerstore.app.model.ManHinh;
import com.acerstore.app.model.Mau;
import com.acerstore.app.model.OCung;
import com.acerstore.app.model.Ram;
import com.acerstore.app.model.SanPhamChiTiets;
import com.acerstore.app.model.SanPhamNew;
import com.acerstore.app.view.IMEIDialog;
import java.awt.Frame;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author ASUS
 */
public class SanPhamChiTiet extends javax.swing.JFrame {

    DefaultTableModel model = new DefaultTableModel();
    private JFrame frame;
    IMEIDialog imei = new IMEIDialog(frame, true);
    SanPhamChiTietDao spctdao = new SanPhamChiTietDao();
    SanPhamDao spdao = new SanPhamDao();
    int index = 0;
    int pageSPCT;
    int numberSPCT = 1;
    int choseSPCT;
    ArrayList<SanPhamChiTiets> spctSize;

    public SanPhamChiTiet() {
        initComponents();
        this.setLocationRelativeTo(null);

        this.fillToTableSPCT(spctdao.getAllSPCT());
        this.comboboxTen();
        this.comboboxMH();
        this.comboboxKT();
        this.comboboxCPU();
        this.comboboxHDH();
        this.comboboxRam();
        this.comboboxOCung();
        this.comboboxMau();
        this.pageSPCT();
        this.qualitySPCT();
        this.fillIMEI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        txtMaSP2 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        txtGia2 = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        rdoConHang3 = new javax.swing.JRadioButton();
        rdoHetHang3 = new javax.swing.JRadioButton();
        jLabel46 = new javax.swing.JLabel();
        txtSoLuong = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cboImei = new javax.swing.JComboBox<>();
        btnImei = new javax.swing.JToggleButton();
        cboTenSP2 = new javax.swing.JComboBox<>();
        jPanel19 = new javax.swing.JPanel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        cboRam4 = new javax.swing.JComboBox<>();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        cboMau = new javax.swing.JComboBox<>();
        jLabel84 = new javax.swing.JLabel();
        jScrollPane13 = new javax.swing.JScrollPane();
        txtMota4 = new javax.swing.JTextArea();
        btnManHinh = new javax.swing.JToggleButton();
        btnRam = new javax.swing.JToggleButton();
        btnAddSPCT = new javax.swing.JToggleButton();
        cboManHinh = new javax.swing.JComboBox<>();
        cboKichThuoc = new javax.swing.JComboBox<>();
        cboCPU = new javax.swing.JComboBox<>();
        cboHeDieuHanh = new javax.swing.JComboBox<>();
        cboOCung = new javax.swing.JComboBox<>();
        btnKichThuoc = new javax.swing.JToggleButton();
        btnCPU = new javax.swing.JToggleButton();
        btnHeDieuHanh = new javax.swing.JToggleButton();
        btnMau = new javax.swing.JToggleButton();
        btnUpdate = new javax.swing.JButton();
        btnOCung = new javax.swing.JToggleButton();
        cboNewForm = new javax.swing.JButton();
        jPanel20 = new javax.swing.JPanel();
        jLabel85 = new javax.swing.JLabel();
        cboGia = new javax.swing.JComboBox<>();
        jLabel86 = new javax.swing.JLabel();
        cboRam5 = new javax.swing.JComboBox<>();
        jLabel87 = new javax.swing.JLabel();
        txtManHinh5 = new javax.swing.JTextField();
        jLabel88 = new javax.swing.JLabel();
        cboCpu = new javax.swing.JComboBox<>();
        jLabel89 = new javax.swing.JLabel();
        txtTimKiem3 = new javax.swing.JTextField();
        jScrollPane8 = new javax.swing.JScrollPane();
        tblSanPhamChiTiet = new javax.swing.JTable();
        btnTruoc = new javax.swing.JButton();
        lblTrang = new javax.swing.JLabel();
        btnSau = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1080, 900));

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));
        jPanel17.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chi tiết sản phẩm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(21, 110, 71))); // NOI18N

        jLabel37.setText("Mã sản phẩm CT");

        jLabel38.setText("Tên sản phẩm");

        jLabel40.setText("Số lượng");

        jLabel41.setText("Giá");

        jLabel42.setText("VNĐ");

        jLabel43.setText("Trạng thái");

        buttonGroup1.add(rdoConHang3);
        rdoConHang3.setText("Còn hàng");

        buttonGroup1.add(rdoHetHang3);
        rdoHetHang3.setText("Hết hàng");
        rdoHetHang3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoHetHang3ActionPerformed(evt);
            }
        });

        jLabel1.setText("Imei");

        cboImei.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnImei.setBackground(new java.awt.Color(21, 110, 71));
        btnImei.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnImei.setForeground(new java.awt.Color(255, 255, 255));
        btnImei.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/acerstore/app/icon/add.png"))); // NOI18N
        btnImei.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImeiActionPerformed(evt);
            }
        });

        cboTenSP2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel38)
                    .addComponent(jLabel37)
                    .addComponent(jLabel40)
                    .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel43)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel17Layout.createSequentialGroup()
                                .addComponent(rdoConHang3)
                                .addGap(18, 18, 18)
                                .addComponent(rdoHetHang3))
                            .addGroup(jPanel17Layout.createSequentialGroup()
                                .addComponent(cboImei, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnImei))))
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel17Layout.createSequentialGroup()
                                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtSoLuong)
                                    .addComponent(txtMaSP2)
                                    .addComponent(cboTenSP2, 0, 160, Short.MAX_VALUE))
                                .addGap(128, 128, 128)
                                .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel17Layout.createSequentialGroup()
                                .addComponent(txtGia2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel42)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnImei)
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel37)
                            .addComponent(txtMaSP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel38)
                            .addComponent(cboTenSP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel46)
                            .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel40)
                                .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel41)
                            .addComponent(txtGia2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel42))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel43)
                            .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(rdoConHang3)
                                .addComponent(rdoHetHang3)))
                        .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel17Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel1))
                            .addGroup(jPanel17Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(cboImei, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel19.setBackground(new java.awt.Color(255, 255, 255));
        jPanel19.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông số kĩ thuật", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(21, 110, 71))); // NOI18N

        jLabel51.setText("Màn hình");

        jLabel52.setText("Ram");

        cboRam4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "8 GB", "16 GB", "32 GB", "64 GB" }));

        jLabel53.setText("Kích thước");

        jLabel54.setText("CPU");

        jLabel55.setText("Hệ điều hành");

        jLabel58.setText("Ổ cứng");

        jLabel83.setText("Màu");

        cboMau.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đen", "Trắng", "Bạc", "Xám" }));

        jLabel84.setText("Mô tả");

        txtMota4.setColumns(20);
        txtMota4.setRows(5);
        jScrollPane13.setViewportView(txtMota4);

        btnManHinh.setBackground(new java.awt.Color(21, 110, 71));
        btnManHinh.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnManHinh.setForeground(new java.awt.Color(255, 255, 255));
        btnManHinh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/acerstore/app/icon/add.png"))); // NOI18N
        btnManHinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManHinhActionPerformed(evt);
            }
        });

        btnRam.setBackground(new java.awt.Color(21, 110, 71));
        btnRam.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRam.setForeground(new java.awt.Color(255, 255, 255));
        btnRam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/acerstore/app/icon/add.png"))); // NOI18N
        btnRam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRamActionPerformed(evt);
            }
        });

        btnAddSPCT.setBackground(new java.awt.Color(21, 110, 71));
        btnAddSPCT.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAddSPCT.setForeground(new java.awt.Color(255, 255, 255));
        btnAddSPCT.setText("Add SPCT");
        btnAddSPCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSPCTActionPerformed(evt);
            }
        });

        cboKichThuoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10x10 nagn1.4kg" }));

        cboCPU.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "intel 3" }));

        cboHeDieuHanh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "windows 11" }));

        cboOCung.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "526" }));

        btnKichThuoc.setBackground(new java.awt.Color(21, 110, 71));
        btnKichThuoc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnKichThuoc.setForeground(new java.awt.Color(255, 255, 255));
        btnKichThuoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/acerstore/app/icon/add.png"))); // NOI18N
        btnKichThuoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKichThuocActionPerformed(evt);
            }
        });

        btnCPU.setBackground(new java.awt.Color(21, 110, 71));
        btnCPU.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCPU.setForeground(new java.awt.Color(255, 255, 255));
        btnCPU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/acerstore/app/icon/add.png"))); // NOI18N
        btnCPU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCPUActionPerformed(evt);
            }
        });

        btnHeDieuHanh.setBackground(new java.awt.Color(21, 110, 71));
        btnHeDieuHanh.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnHeDieuHanh.setForeground(new java.awt.Color(255, 255, 255));
        btnHeDieuHanh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/acerstore/app/icon/add.png"))); // NOI18N
        btnHeDieuHanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHeDieuHanhActionPerformed(evt);
            }
        });

        btnMau.setBackground(new java.awt.Color(21, 110, 71));
        btnMau.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMau.setForeground(new java.awt.Color(255, 255, 255));
        btnMau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/acerstore/app/icon/add.png"))); // NOI18N
        btnMau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMauActionPerformed(evt);
            }
        });

        btnUpdate.setText("update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnOCung.setBackground(new java.awt.Color(21, 110, 71));
        btnOCung.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnOCung.setForeground(new java.awt.Color(255, 255, 255));
        btnOCung.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/acerstore/app/icon/add.png"))); // NOI18N
        btnOCung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOCungActionPerformed(evt);
            }
        });

        cboNewForm.setText("New Form");
        cboNewForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboNewFormActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel58, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel53)
                            .addComponent(jLabel54, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel55, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cboOCung, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboRam4, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboManHinh, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboKichThuoc, 0, 140, Short.MAX_VALUE)
                            .addComponent(cboCPU, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboHeDieuHanh, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel19Layout.createSequentialGroup()
                                .addComponent(btnManHinh)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel83, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboMau, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnMau))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel19Layout.createSequentialGroup()
                                .addComponent(btnOCung)
                                .addGap(84, 84, 84)
                                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnAddSPCT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(cboNewForm))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel19Layout.createSequentialGroup()
                                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnKichThuoc)
                                    .addComponent(btnCPU)
                                    .addComponent(btnRam)
                                    .addComponent(btnHeDieuHanh))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel19Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel84)))))
                    .addComponent(jLabel51))
                .addContainerGap(172, Short.MAX_VALUE))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel19Layout.createSequentialGroup()
                                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnMau)
                                    .addComponent(btnManHinh)
                                    .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel51)
                                        .addComponent(jLabel83)
                                        .addComponent(cboMau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cboManHinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel52)
                                        .addComponent(cboRam4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnRam))
                                .addGap(24, 24, 24)
                                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel19Layout.createSequentialGroup()
                                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel53)
                                                .addComponent(cboKichThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(btnKichThuoc, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel54)
                                                .addComponent(cboCPU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(btnCPU))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel55)
                                            .addComponent(cboHeDieuHanh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel19Layout.createSequentialGroup()
                                        .addComponent(jLabel84)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(btnHeDieuHanh))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel58)
                                .addComponent(cboOCung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnAddSPCT)
                                .addComponent(cboNewForm))))
                    .addComponent(btnOCung))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(btnUpdate))
        );

        jPanel20.setBackground(new java.awt.Color(255, 255, 255));
        jPanel20.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bộ lọc", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(21, 110, 71))); // NOI18N

        jLabel85.setText("Giá");

        cboGia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dưới 10 triệu", "Từ 10 triệu đến 20 triệu", "Trên 20 triệu", " " }));
        cboGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboGiaActionPerformed(evt);
            }
        });

        jLabel86.setText("Ram");

        cboRam5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "8 GB", "16 GB", "32 GB", "64 GB" }));
        cboRam5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cboRam5MouseClicked(evt);
            }
        });
        cboRam5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboRam5ActionPerformed(evt);
            }
        });

        jLabel87.setText("Màn hình");

        txtManHinh5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtManHinh5ActionPerformed(evt);
            }
        });
        txtManHinh5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtManHinh5KeyReleased(evt);
            }
        });

        jLabel88.setText("CPU");

        cboCpu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Intel core i3", "Intel core i5", "Intel core i7" }));
        cboCpu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cboCpuMouseClicked(evt);
            }
        });
        cboCpu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboCpuActionPerformed(evt);
            }
        });

        jLabel89.setText("Tìm kiếm");

        txtTimKiem3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiem3KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTimKiem3)
                    .addComponent(cboCpu, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtManHinh5, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboRam5, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel20Layout.createSequentialGroup()
                        .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel85, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel87)
                            .addComponent(jLabel89, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel88)
                            .addComponent(jLabel86))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(cboGia, javax.swing.GroupLayout.Alignment.LEADING, 0, 212, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel85)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cboGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel86)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cboRam5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel87)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtManHinh5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel88)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboCpu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel89)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTimKiem3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        tblSanPhamChiTiet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sản phẩm chi tiêt", "Tên sản phẩm", "Số lượng", "Giá", "Màn hình", "Ram", "Kích thước", "CPU", "Hệ điều hành", "Ổ cứng", "Màu", "Trạng thái", "Mô tả"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSanPhamChiTiet.setPreferredSize(new java.awt.Dimension(1080, 900));
        tblSanPhamChiTiet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSanPhamChiTietMouseClicked(evt);
            }
        });
        jScrollPane8.setViewportView(tblSanPhamChiTiet);

        btnTruoc.setText("<<");
        btnTruoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTruocActionPerformed(evt);
            }
        });

        lblTrang.setText("Trang");

        btnSau.setText(">>");
        btnSau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSauActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 843, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(266, 266, 266)
                        .addComponent(btnTruoc)
                        .addGap(33, 33, 33)
                        .addComponent(lblTrang, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnSau)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTruoc)
                            .addComponent(btnSau)
                            .addComponent(lblTrang)))
                    .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 749, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblSanPhamChiTietMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSanPhamChiTietMouseClicked
        // TODO add your handling code here:
        index = tblSanPhamChiTiet.getSelectedRow();
        showDetailSPCT(index);

        btnUpdate.setEnabled(true);
    }//GEN-LAST:event_tblSanPhamChiTietMouseClicked

    private void cboGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboGiaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cboGiaActionPerformed

    private void txtManHinh5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtManHinh5ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtManHinh5ActionPerformed

    private void txtManHinh5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtManHinh5KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtManHinh5KeyReleased

    private void txtTimKiem3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiem3KeyReleased
        // TODO add your handling code here:
        model = (DefaultTableModel) tblSanPhamChiTiet.getModel();
        TableRowSorter<DefaultTableModel> ob = new TableRowSorter<>(model);
        tblSanPhamChiTiet.setRowSorter(ob);
        ob.setRowFilter(RowFilter.regexFilter(String.valueOf(txtTimKiem3.getText())));
    }//GEN-LAST:event_txtTimKiem3KeyReleased

    private void cboCpuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboCpuMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cboCpuMouseClicked

    private void cboRam5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboRam5MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_cboRam5MouseClicked

    private void btnManHinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManHinhActionPerformed
        // TODO add your handling code here:
        this.addMH();
    }//GEN-LAST:event_btnManHinhActionPerformed

    private void btnAddSPCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSPCTActionPerformed
        // TODO add your handling code here:
//        this.sanphamct(1);
        this.addSPCt();

    }//GEN-LAST:event_btnAddSPCTActionPerformed

    private void rdoHetHang3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoHetHang3ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_rdoHetHang3ActionPerformed

    private void btnRamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRamActionPerformed
        // TODO add your handling code here:
        this.addRam();
    }//GEN-LAST:event_btnRamActionPerformed

    private void btnKichThuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKichThuocActionPerformed
        // TODO add your handling code here:
        this.addKT();
    }//GEN-LAST:event_btnKichThuocActionPerformed

    private void btnCPUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCPUActionPerformed
        // TODO add your handling code here:
        this.addCPU();
    }//GEN-LAST:event_btnCPUActionPerformed

    private void btnHeDieuHanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHeDieuHanhActionPerformed
        // TODO add your handling code here:
        this.HeDieuHanh();
    }//GEN-LAST:event_btnHeDieuHanhActionPerformed

    private void btnImeiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImeiActionPerformed
        // TODO add your handling code here:
        this.addIMEI();
    }//GEN-LAST:event_btnImeiActionPerformed

    private void btnMauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMauActionPerformed
        // TODO add your handling code here:
        this.addMau();
    }//GEN-LAST:event_btnMauActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        this.updateSPCT();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void cboRam5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboRam5ActionPerformed
        // TODO add your handling code here:
        model = (DefaultTableModel) tblSanPhamChiTiet.getModel();
        TableRowSorter<DefaultTableModel> r = new TableRowSorter<>(model);
        tblSanPhamChiTiet.setRowSorter(r);
        r.setRowFilter(RowFilter.regexFilter(String.valueOf(cboRam5.getSelectedItem())));
    }//GEN-LAST:event_cboRam5ActionPerformed

    private void cboCpuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCpuActionPerformed
        // TODO add your handling code here:
        model = (DefaultTableModel) tblSanPhamChiTiet.getModel();
        TableRowSorter<DefaultTableModel> cpu = new TableRowSorter<>(model);
        tblSanPhamChiTiet.setRowSorter(cpu);
        cpu.setRowFilter(RowFilter.regexFilter(String.valueOf(cboCpu.getSelectedItem())));
    }//GEN-LAST:event_cboCpuActionPerformed

    private void btnTruocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTruocActionPerformed
        // TODO add your handling code here:
        if (pageSPCT <= numberSPCT) {
            if (pageSPCT == 1) {
                return;
            }
            pageSPCT--;
            pageSPCT();
            qualitySPCT();
            fillToTableSPCT(spctdao.getAllSPCT());

        }
    }//GEN-LAST:event_btnTruocActionPerformed

    private void btnOCungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOCungActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnOCungActionPerformed

    private void btnSauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSauActionPerformed
        // TODO add your handling code here:
        if (pageSPCT >= 1 && pageSPCT < numberSPCT) {
            pageSPCT++;
            pageSPCT();
            qualitySPCT();
            fillToTableSPCT(spctdao.getAllSPCT());
        }
    }//GEN-LAST:event_btnSauActionPerformed

    private void cboNewFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboNewFormActionPerformed
        // TODO add your handling code here:
        this.newForm();
    }//GEN-LAST:event_cboNewFormActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SanPhamChiTiet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SanPhamChiTiet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SanPhamChiTiet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SanPhamChiTiet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SanPhamChiTiet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnAddSPCT;
    private javax.swing.JToggleButton btnCPU;
    private javax.swing.JToggleButton btnHeDieuHanh;
    private javax.swing.JToggleButton btnImei;
    private javax.swing.JToggleButton btnKichThuoc;
    private javax.swing.JToggleButton btnManHinh;
    private javax.swing.JToggleButton btnMau;
    private javax.swing.JToggleButton btnOCung;
    private javax.swing.JToggleButton btnRam;
    private javax.swing.JButton btnSau;
    private javax.swing.JButton btnTruoc;
    private javax.swing.JButton btnUpdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cboCPU;
    private javax.swing.JComboBox<String> cboCpu;
    private javax.swing.JComboBox<String> cboGia;
    private javax.swing.JComboBox<String> cboHeDieuHanh;
    private javax.swing.JComboBox<String> cboImei;
    private javax.swing.JComboBox<String> cboKichThuoc;
    private javax.swing.JComboBox<String> cboManHinh;
    public javax.swing.JComboBox<String> cboMau;
    private javax.swing.JButton cboNewForm;
    private javax.swing.JComboBox<String> cboOCung;
    public javax.swing.JComboBox<String> cboRam4;
    private javax.swing.JComboBox<String> cboRam5;
    private javax.swing.JComboBox<String> cboTenSP2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JLabel lblTrang;
    public javax.swing.JRadioButton rdoConHang3;
    public javax.swing.JRadioButton rdoHetHang3;
    private javax.swing.JTable tblSanPhamChiTiet;
    public javax.swing.JTextField txtGia2;
    public javax.swing.JTextField txtMaSP2;
    private javax.swing.JTextField txtManHinh5;
    public javax.swing.JTextArea txtMota4;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTimKiem3;
    // End of variables declaration//GEN-END:variables

    private void showDetailSPCT(int index) {
        SanPhamChiTiets spct = spctdao.getAllSPCT().get(index);
        txtMaSP2.setText(spct.getMaSpct());
//        txtTenSP2.setText(spct.getSp().getTenSP());
        cboImei.setSelectedItem(spct.getIm().getMa());
        txtSoLuong.setText(spct.getSoluong() + "");
        txtGia2.setText(spct.getGia() + "");
        cboManHinh.setSelectedItem(spct.getMh().getTenMh());
        cboRam4.setSelectedItem(spct.getRa().getTenRam());
        cboCpu.setSelectedItem(spct.getKt().getTenKT());
        cboHeDieuHanh.setSelectedItem(spct.getHdh().getTenHDH());
        cboOCung.setSelectedItem(spct.getOc().getTenOCung());
        cboMau.setSelectedItem(spct.getMa().getTenMau());
        rdoConHang3.setSelected(spct.getSp().isTrangThai());
        rdoHetHang3.setSelected(!spct.getSp().isTrangThai());
        txtMota4.setText(spct.getSp().getMota());
        tblSanPhamChiTiet.setRowSelectionInterval(index, index);
    }

    private void fillToTableSPCT(List<SanPhamChiTiets> spct) {
        model = (DefaultTableModel) tblSanPhamChiTiet.getModel();
        model.setRowCount(0);
        if (spct != null) {
            for (SanPhamChiTiets s : spct) {
                model.addRow(new Object[]{
                    s.getMaSpct(),
                    s.getSp().getTenSP(),
                    s.getSoluong(),
                    s.getGia(),
                    s.getMh().getTenMh(),
                    s.getRa().getTenRam(),
                    s.getKt().getTenKT(),
                    s.getCp().getTenCPU(),
                    s.getHdh().getTenHDH(),
                    s.getOc().getTenOCung(),
                    s.getMa().getTenMau(),
                    s.getSp().isTrangThai() ? "Còn hàng" : "Hết hàng",
                    s.getSp().getMota()
                });
            }
        }
        cboImei.setSelectedItem(null);
    }

    private boolean checkDataSPCT() {
        if (txtMaSP2.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "không để trống");
            txtMaSP2.requestFocus();
            return false;
        }
//        if (txtTenSP2.getText().isEmpty()) {
//            JOptionPane.showMessageDialog(this, "không để trống");
//            txtTenSP2.requestFocus();
//            return false;
//        }
        if (txtSoLuong.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "không để trống");
            txtSoLuong.requestFocus();
            return false;
        }
        if (txtGia2.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "không để trống");
            txtGia2.requestFocus();
            return false;
        }
        return true;
    }

    private SanPhamChiTiets readDataSPCT() {
//        String maSP = txtMaSP2.getText();
//        String tenSP = txtTenSP2.getText();
//        String Imei = txtImei.getText();
//        int soLuong = Integer.parseInt(txtSoLuong.getText());
//        double gia = Double.parseDouble(txtGia2.getText());
//        String manHinh = (String) cboManHinh.getSelectedItem();
//        String ram = (String) cboRam4.getSelectedItem();
//        String kichThuoc = (String)cboKichThuoc.getSelectedItem();
//        String Cpu = (String) cboCPU.getSelectedItem();
//        String heDieuHanh = (String) cboHeDieuHanh.getSelectedItem();
//        String oCung =  (String)cboOCung.getSelectedItem();
//        String mau = (String) cboMau.getSelectedItem();
//        boolean trangthai = rdoConHang3.isSelected();
//        String mota = txtMota4.getText();
//        return new SanPhamChiTiets(maSP, tenSP, Imei, soLuong, gia, manHinh, ram, kichThuoc, Cpu, heDieuHanh, oCung, mau, trangthai, mota);
        return null;
    }

    private void addSPCt() {
        String maspct = txtMaSP2.getText();
        int soluong = Integer.parseInt(txtSoLuong.getText());
        double gia = Double.parseDouble(txtGia2.getText());
        SanPhamNew sp = spdao.getAll().get(cboTenSP2.getSelectedIndex());
        String trangthai = String.valueOf(sp.isTrangThai());
        String mota = sp.getMota();
        int idsp = sp.getSpid();
        ManHinh mh = spctdao.getMH().get(cboManHinh.getSelectedIndex());
        int idmanhinh = mh.getIdMh();
        Ram ram = spctdao.getRam().get(cboRam4.getSelectedIndex());
        int idram = ram.getIdRam();
        KichThuoc kichthuoc = spctdao.getKichThuoc().get(cboKichThuoc.getSelectedIndex());
        int idkt = kichthuoc.getIdKT();
        CPU cpu = spctdao.getCPU().get(cboCPU.getSelectedIndex());
        int idcpu = cpu.getIdCPU();
        HeDieuHanh hedieuhanh = spctdao.getHeDieuHanh().get(cboHeDieuHanh.getSelectedIndex());
        int idhdh = hedieuhanh.getIdHDH();
        OCung ocung = spctdao.getOCung().get(cboOCung.getSelectedIndex());
        int idocung = ocung.getIdOCung();
        Mau mau = spctdao.getMau().get(cboMau.getSelectedIndex());
        int idmau = mau.getIdMau();
        Imei imei = spctdao.getIMEI().get(cboImei.getSelectedIndex());
        int ImeiId = imei.getIdimei();
        if (checkSanPhamCT()) {
            if (spctdao.AddSPdedail(maspct, soluong, gia, idmanhinh, idram, idkt, idcpu, idhdh, idocung, idmau, ImeiId, idsp) > 0) {
                JOptionPane.showMessageDialog(this, "add successful");
                fillToTableSPCT(spctdao.getAllSPCT());
            } else {
                JOptionPane.showMessageDialog(this, "add failed");
            }
        }

    }

    public boolean checkSanPhamCT() {
        int soluong;
        double gia;
        if (txtSoLuong.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Chưa nhập số lượng");
            return false;
        } else {
            try {
                soluong = Integer.parseInt(txtSoLuong.getText());
                if (soluong <= 0) {
                    JOptionPane.showMessageDialog(this, "Số lượng phải lớn hơn 0");
                    return false;
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Sai định dạng số");
            }
        }

        if (txtGia2.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Chưa nhập đơn giá");
            txtGia2.requestFocus();
            return false;
        } else {
            try {
                gia = Double.parseDouble(txtGia2.getText());
                if (gia <= 0) {
                    JOptionPane.showMessageDialog(this, "Đơn giá phải lớn hơn = 0");
                    txtGia2.requestFocus();
                    return false;
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Sai định dạng đơn giá");
                txtGia2.requestFocus();
                return false;
            }
        }
        return true;
    }

    public void comboboxTen() {
        DefaultComboBoxModel<String> ten = (DefaultComboBoxModel<String>) cboTenSP2.getModel();
        ten.removeAllElements();
        for (SanPhamNew spn : spdao.getAll()) {
            ten.addElement(spn.getTenSP());
        }
    }

    private void addMH() {
        ManHinhhJDaLog mh = new ManHinhhJDaLog(frame, true);
        mh.setVisible(true);
    }

    public void comboboxMH() {
        DefaultComboBoxModel<String> Mh = (DefaultComboBoxModel) cboManHinh.getModel();
        Mh.removeAllElements();
        for (ManHinh mh : spctdao.getMH()) {
            Mh.addElement(mh.getTenMh());
        }
    }

    public void comboboxRam() {
        DefaultComboBoxModel<String> ra = (DefaultComboBoxModel) cboRam4.getModel();
        DefaultComboBoxModel<String> ram = (DefaultComboBoxModel) cboRam5.getModel();
        ra.removeAllElements();
        ram.removeAllElements();
        for (Ram r : spctdao.getRam()) {
            ra.addElement(r.getTenRam());
            ram.addElement(r.getTenRam());
        }
    }

    public void comboboxKT() {
        DefaultComboBoxModel<String> kt = (DefaultComboBoxModel) cboKichThuoc.getModel();
        kt.removeAllElements();
        for (KichThuoc k : spctdao.getKichThuoc()) {
            kt.addElement(k.getTenKT());
        }
    }

    public void comboboxCPU() {
        DefaultComboBoxModel<String> cpu = (DefaultComboBoxModel) cboCPU.getModel();
        DefaultComboBoxModel<String> cpu2 = (DefaultComboBoxModel) cboCpu.getModel();
        cpu.removeAllElements();
        cpu2.removeAllElements();
        for (CPU c : spctdao.getCPU()) {
            cpu.addElement(c.getTenCPU());
            cpu2.addElement(c.getTenCPU());
        }
    }

    public void comboboxHDH() {
        DefaultComboBoxModel<String> hdh = (DefaultComboBoxModel) cboHeDieuHanh.getModel();
        hdh.removeAllElements();
        for (HeDieuHanh h : spctdao.getHeDieuHanh()) {
            hdh.addElement(h.getTenHDH());
        }
    }

    public void comboboxOCung() {
        DefaultComboBoxModel<String> Ocung = (DefaultComboBoxModel) cboOCung.getModel();
        Ocung.removeAllElements();
        for (OCung o : spctdao.getOCung()) {
            Ocung.addElement(o.getTenOCung());
        }
    }

    public void comboboxMau() {
        DefaultComboBoxModel<String> mau = (DefaultComboBoxModel) cboMau.getModel();
        mau.removeAllElements();
        for (Mau m : spctdao.getMau()) {
            mau.addElement(m.getTenMau());
        }
    }

    private void addRam() {
        new RammJDaLog(frame, true).setVisible(true);
    }

    private void addKT() {
        new KichThuoccJDaLog(frame, true).setVisible(true);
    }

    private void addCPU() {
        new CPUuJDaLog(frame, true).setVisible(true);
    }

    private void HeDieuHanh() {
        new HeDieuHanhhJDaLog(frame, true).setVisible(true);
    }

    private void OCung() {
        new OCunggJDaLog(frame, true).setVisible(true);
    }

    private void addMau() {
        new MauJDaLog(frame, true).setVisible(true);
    }

    void pageSPCT() {
        choseSPCT = (numberSPCT - 1) * 5;
    }

    void qualitySPCT() {
        spctSize = spctdao.getSPCT();
        if (spctSize != null) {
            pageSPCT = (int) Math.ceil(spctSize.size() / 5.0);
            lblTrang.setText(numberSPCT + "/" + pageSPCT);
        } else {
            lblTrang.setText("Error: Data is null");
        }
    }

    public void fillIMEI() {
        DefaultComboBoxModel<String> ImeiModel = (DefaultComboBoxModel) cboImei.getModel();
        ImeiModel.removeAllElements();
        for (Imei i : spctdao.getIMEI()) {
            ImeiModel.addElement(i.getMa());
        }
//        Imei[] IMEI = new Imei[listIMEI.size()];
//        for (int i = 0; i < listIMEI.size(); i++) {
//            IMEI[i] = listIMEI.get(i);
//        }
//        cboImei.setModel(new javax.swing.DefaultComboBoxModel(IMEI));
//        cboImei.setSelectedIndex(-1);
    }

    private void updateLabelCount() {
        try {
            Connection conn = DBConnection.getConnection();

            String sqlCount = "SELECT COUNT(*) AS total FROM IMEI";
            PreparedStatement pstmtCount = conn.prepareStatement(sqlCount);
            ResultSet rsCount = pstmtCount.executeQuery();
            rsCount.next();

            int totalCount = rsCount.getInt("total");
            txtSoLuong.setText("" + totalCount);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    void addIMEI() {
        imei.setVisible(true);
        updateLabelCount();
        fillIMEI();
    }

    private void updateSPCT() {
        double gia = Double.parseDouble(txtGia2.getText());
        SanPhamNew sp = spdao.getAll().get(cboTenSP2.getSelectedIndex());
        String mota = sp.getMota();
        int idsp = sp.getSpid();
        ManHinh mh = spctdao.getMH().get(cboManHinh.getSelectedIndex());
        int idmanhinh = mh.getIdMh();
        Ram ram = spctdao.getRam().get(cboRam4.getSelectedIndex());
        int idram = ram.getIdRam();
        KichThuoc kichthuoc = spctdao.getKichThuoc().get(cboKichThuoc.getSelectedIndex());
        int idkt = kichthuoc.getIdKT();
        CPU cpu = spctdao.getCPU().get(cboCPU.getSelectedIndex());
        int idcpu = cpu.getIdCPU();
        HeDieuHanh hedieuhanh = spctdao.getHeDieuHanh().get(cboHeDieuHanh.getSelectedIndex());
        int idhdh = hedieuhanh.getIdHDH();
        OCung ocung = spctdao.getOCung().get(cboOCung.getSelectedIndex());
        int idocung = ocung.getIdOCung();
        Mau mau = spctdao.getMau().get(cboMau.getSelectedIndex());
        int idmau = mau.getIdMau();
        if (spctdao.UpdateSPdedail(gia, idmanhinh, idram, idkt, idcpu, idhdh, idocung, idmau, mota) > 0) {
            JOptionPane.showMessageDialog(this, "update successful");
            this.fillToTableSPCT(spctdao.getAllSPCT());
        } else {
            JOptionPane.showMessageDialog(this, "update failed");
        }
        this.newForm();
        btnUpdate.setEnabled(false);
    }

    private void newForm() {
        txtMaSP2.setText("");
        cboTenSP2.setSelectedItem(null);
        txtSoLuong.setText("");
        txtGia2.setText("");
        cboImei.setSelectedItem(null);
        cboManHinh.setSelectedItem(null);
        cboRam4.setSelectedItem(null);
        cboKichThuoc.setSelectedItem(null);
        cboCPU.setSelectedItem(null);
        cboHeDieuHanh.setSelectedItem(null);
        cboOCung.setSelectedItem(null);
        cboMau.setSelectedItem(null);
        txtMota4.setText("");
    }
    private void updateTrangThai(){
        int soluong = Integer.parseInt(txtSoLuong.getText());
        if(spdao.checksoLuong(soluong)>0){
            fillToTableSPCT(spctdao.getAllSPCT());
        }
        else{
            
        }
    }
}
